# Generated by Django 5.1.2 on 2024-10-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='owner_bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barmessages',
            name='where_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.bar'),
        ),
        migrations.AddField(
            model_name='bar',
            name='bar_category',
            field=models.ManyToManyField(to='bars.category'),
        ),
        migrations.AddField(
            model_name='imgbar',
            name='where_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.bar'),
        ),
    ]
