# Generated by Django 5.1.2 on 2024-10-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
