# Generated by Django 5.1.2 on 2024-10-29 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_bar_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bar',
            new_name='Bars',
        ),
    ]
