# Generated by Django 5.1.2 on 2024-10-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_favoritebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritebar',
            name='bar',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_bar', to='bars.bars'),
        ),
    ]
