# Generated by Django 5.1.2 on 2024-10-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0007_barmessages_owner_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='bar_category',
            field=models.ManyToManyField(db_index=True, to='bars.category'),
        ),
        migrations.AlterField(
            model_name='bars',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bars',
            name='public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
