# Generated by Django 5.1.2 on 2024-10-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0008_alter_bars_bar_category_alter_bars_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
